title: RELEvaNT Project Website
logo: /assets/relevant.png
description: This is the website for project RELEvaNT, funded by the Portuguese Foundation for Sciente and Technology under reference PTDC/CCI-COM/5060/2021.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
